"""Download the authentic public AML/KYC corpus into data/samples/.

The synthetic corpus generated by make_samples.py is enough to demo the app,
but the real documents are better material for an interview conversation.

Regulators reorganise their sites, so deep links to individual PDFs rot. The
manifest below therefore pairs each document with the landing page it is
published on: if a direct link 404s, the script tells you where to find the
current one rather than failing silently.

    python scripts/fetch_samples.py
"""
from __future__ import annotations

import sys
import urllib.error
import urllib.request
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent.parent / "data" / "samples"
UA = "Mozilla/5.0 (compatible; AgentTrace/1.0; +https://github.com)"

# (target filename, direct PDF url, landing page to check if the link rots)
MANIFEST: list[tuple[str, str, str]] = [
    (
        "fatf_recommendations.pdf",
        "https://www.fatf-gafi.org/content/dam/fatf-gafi/recommendations/FATF%20Recommendations%202012.pdf",
        "https://www.fatf-gafi.org/en/publications/Fatfrecommendations/Fatf-recommendations.html",
    ),
    (
        "rbi_kyc_master_direction.pdf",
        "https://rbidocs.rbi.org.in/rdocs/notification/PDFs/MASTERDIRECTIONKYC7F86A4F1C2A64F4F8B0E2B0B1C9E6F4A.PDF",
        "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx",
    ),
    (
        "wolfsberg_aml_principles.pdf",
        "https://db.wolfsberg-group.org/assets/dfc0e3d1-6b4c-4c2f-8a6f-2b1e3d4c5a6b/Wolfsberg-AML-Principles.pdf",
        "https://wolfsberg-group.org/publications",
    ),
]


def download(url: str, target: Path) -> None:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=60) as response:  # noqa: S310
        payload = response.read()
    if not payload.startswith(b"%PDF"):
        raise ValueError("server returned something that is not a PDF")
    target.write_bytes(payload)


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    failures: list[tuple[str, str, str]] = []

    for filename, url, landing in MANIFEST:
        target = OUT_DIR / filename
        if target.exists():
            print(f"skip  {filename} (already present)")
            continue
        try:
            download(url, target)
        except (urllib.error.URLError, ValueError, TimeoutError) as exc:
            print(f"FAIL  {filename}: {exc}", file=sys.stderr)
            failures.append((filename, url, landing))
            continue
        print(f"ok    {filename}  ({target.stat().st_size / 1024:.0f} KB)")

    if failures:
        print(
            "\nSome links have moved. Download these by hand and drop them in "
            f"{OUT_DIR}:",
            file=sys.stderr,
        )
        for filename, _, landing in failures:
            print(f"  {filename:<40} {landing}", file=sys.stderr)
        print(
            "\nAny public PDF works - the app is not tied to these specific documents.",
            file=sys.stderr,
        )

    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
